// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6MuSm2fY1PQnGtGlKhV3GwUneQ5j9lx0',
    appId: '1:746060492587:web:f6a24cf68e2f727cf7df6e',
    messagingSenderId: '746060492587',
    projectId: 'movie-rs-7fc7a',
    authDomain: 'movie-rs-7fc7a.firebaseapp.com',
    storageBucket: 'movie-rs-7fc7a.firebasestorage.app',
    measurementId: 'G-FDBQ40SXPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPVxk8kkEMXcaEGsbtV8kLA0iXDKJxi6E',
    appId: '1:746060492587:android:542478d29bf0320df7df6e',
    messagingSenderId: '746060492587',
    projectId: 'movie-rs-7fc7a',
    storageBucket: 'movie-rs-7fc7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXW9ENnb1Q7aW2jUws6CXZ2mreDZnYIj8',
    appId: '1:746060492587:ios:570304dd4c42dfdcf7df6e',
    messagingSenderId: '746060492587',
    projectId: 'movie-rs-7fc7a',
    storageBucket: 'movie-rs-7fc7a.firebasestorage.app',
    iosBundleId: 'com.example.ddwChutti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXW9ENnb1Q7aW2jUws6CXZ2mreDZnYIj8',
    appId: '1:746060492587:ios:570304dd4c42dfdcf7df6e',
    messagingSenderId: '746060492587',
    projectId: 'movie-rs-7fc7a',
    storageBucket: 'movie-rs-7fc7a.firebasestorage.app',
    iosBundleId: 'com.example.ddwChutti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6MuSm2fY1PQnGtGlKhV3GwUneQ5j9lx0',
    appId: '1:746060492587:web:99da5043658e35d9f7df6e',
    messagingSenderId: '746060492587',
    projectId: 'movie-rs-7fc7a',
    authDomain: 'movie-rs-7fc7a.firebaseapp.com',
    storageBucket: 'movie-rs-7fc7a.firebasestorage.app',
    measurementId: 'G-T0EXY738CZ',
  );
}
